-- Copy these table definitions to the Supabase SQL Editor
-- and run them to create the tables in your database.

-- Table: messages

create table public.messages (
  id uuid not null default gen_random_uuid (),
  room_id bigint null,
  sender_id uuid null,
  content text not null,
  created_at timestamp without time zone null default now(),
  constraint messages_pkey primary key (id),
  constraint messages_room_id_fkey foreign KEY (room_id) references room (id) on delete CASCADE,
  constraint messages_sender_id_fkey foreign KEY (sender_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

-- table: room

create table public.room (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text null,
  description text null,
  room_thumbnail text null,
  room_creator uuid null,
  constraint room_pkey primary key (id),
  constraint room_room_creator_fkey foreign KEY (room_creator) references auth.users (id)
) TABLESPACE pg_default;

-- table: users

create table public.users (
  id bigint generated by default as identity not null,
  user_id uuid null,
  display_name text null,
  constraint users_pkey primary key (id),
  constraint users_user_id_fkey foreign KEY (user_id) references auth.users (id)
) TABLESPACE pg_default;

-- table: video_queue

create table public.video_queue (
  id uuid not null default gen_random_uuid (),
  room_id bigint null,
  video_url text not null,
  position integer not null,
  added_at timestamp without time zone null default now(),
  requester text null,
  video_title text null,
  video_thumbnail text null,
  constraint video_queue_pkey primary key (id),
  constraint video_queue_room_id_fkey foreign KEY (room_id) references room (id) on delete CASCADE
) TABLESPACE pg_default;